"""Update ProcessingJob model

Revision ID: 12742110e2cc
Revises: 8a01c39e1ded
Create Date: 2026-08-25 09:59:40.394682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12742110e2cc'
down_revision: Union[str, Sequence[str], None] = '8a01c39e1ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_jobs', sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('processing_jobs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('processing_jobs', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('processing_jobs', sa.Column('job_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE jobstatus ADD VALUE IF NOT EXISTS 'QUEUED'")
        op.execute("ALTER TYPE jobstatus RENAME VALUE 'RUNNING' TO 'PROCESSING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processing_jobs', 'job_metadata')
    op.drop_column('processing_jobs', 'worker_id')
    op.drop_column('processing_jobs', 'retry_count')
    op.drop_column('processing_jobs', 'failed_at')
    op.drop_column('processing_jobs', 'queued_at')
    # ### end Alembic commands ###
