from typing import Any, Dict
from abc import ABC, abstractmethod
from sqlalchemy.ext.asyncio import AsyncSession
from app.models.processing import ProcessingJob
from app.models.document import Document

class ProcessingStage(ABC):
    """
    Base class for a processing pipeline stage.
    Each stage should handle a specific chunk of work (e.g., OCR, Extraction).
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Name of the stage."""
        pass

    @abstractmethod
    async def execute(self, session: AsyncSession, job: ProcessingJob, document: Document) -> Dict[str, Any]:
        """
        Executes the stage logic.
        
        Args:
            session: The SQLAlchemy AsyncSession for DB operations.
            job: The ProcessingJob model instance.
            document: The Document model instance.
            
        Returns:
            A dictionary containing structured results or metadata generated by the stage.
            This may be merged into job_metadata.
            
        Raises:
            Exception if the stage fails in a controlled or uncontrolled manner.
        """
        pass
